#version: '3.9' #docker version
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" #sync project dir with container web dir
    ports:
      - "8080:80"
      - "443:443" # for future ssl traffic
  db:
    image: mysql:9.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shopping_cart
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  db_data: